# Generated by Django 5.2 on 2026-07-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_notification'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE messaging_message DROP COLUMN IF EXISTS created_at;",
            reverse_sql="ALTER TABLE messaging_message ADD COLUMN created_at timestamp with time zone;",
        ),
    ]
