# Generated by Django 5.2 on 2026-06-14 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('activities', models.TextField()),
                ('skills_acquired', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='logbook_attachments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
