# Generated by Django 5.2 on 2026-06-28 19:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='logbookentry',
            unique_together={('student', 'week_number')},
        ),
    ]
